# Generated by Django 6.0.2 on 2026-03-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_options_alter_ticket_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(base_price__gte=0),
                name="booking_base_price_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(discount_amount__gte=0),
                name="booking_discount_amount_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(total_price__gte=0),
                name="booking_total_price_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(discount_amount__lte=models.F("base_price")),
                name="booking_discount_not_above_base_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(amount__gte=0),
                name="payment_amount_gte_zero",
            ),
        ),
    ]
