# Generated by Django 6.0.2 on 2026-03-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
