# Generated by Django 6.0.2 on 2026-03-24 11:03

import django.db.models.deletion
from django.db import migrations, models


def assign_uncategorized_to_legacy_events(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    Category = apps.get_model("events", "Category")

    if not Event.objects.filter(category__isnull=True).exists():
        return

    uncategorized, _ = Category.objects.get_or_create(
        name="Uncategorized",
        defaults={"description": "Fallback category for legacy events."},
    )
    Event.objects.filter(category__isnull=True).update(category=uncategorized)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_parking_fields"),
    ]

    operations = [
        migrations.RunPython(assign_uncategorized_to_legacy_events, noop_reverse),
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["date", "-created_at"]},
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="events.category",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(price__gte=0),
                name="event_price_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(capacity__gte=1),
                name="event_capacity_gte_one",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(latitude__isnull=True, longitude__isnull=True)
                    | models.Q(latitude__isnull=False, longitude__isnull=False)
                ),
                name="event_coordinates_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(latitude__isnull=True) | models.Q(latitude__gte=-90, latitude__lte=90),
                name="event_latitude_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(longitude__isnull=True) | models.Q(longitude__gte=-180, longitude__lte=180),
                name="event_longitude_valid",
            ),
        ),
    ]
