# Generated by Django 6.0.2 on 2026-03-26 00:00

from django.db import migrations, models


def backfill_verified_at(apps, schema_editor):
    StudentVerification = apps.get_model("users", "StudentVerification")
    StudentVerification.objects.filter(
        status="APPROVED",
        verified_at__isnull=True,
        reviewed_at__isnull=False,
    ).update(verified_at=models.F("reviewed_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_auth_provider_user_google_sub_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentverification",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_verified_at, migrations.RunPython.noop),
    ]
